Name:               alertmanager-stable-kube-prometheus-sta-alertmanager
Namespace:          default
CreationTimestamp:  Thu, 10 Jun 2021 17:00:26 -0600
Selector:           alertmanager=stable-kube-prometheus-sta-alertmanager,app=alertmanager,app.kubernetes.io/instance=stable-kube-prometheus-sta-alertmanager,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=alertmanager,app.kubernetes.io/version=0.22.2
Labels:             app=kube-prometheus-stack-alertmanager
                    app.kubernetes.io/instance=stable
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/part-of=kube-prometheus-stack
                    app.kubernetes.io/version=16.6.1
                    chart=kube-prometheus-stack-16.6.1
                    heritage=Helm
                    release=stable
Annotations:        meta.helm.sh/release-name: stable
                    meta.helm.sh/release-namespace: default
                    prometheus-operator-input-hash: 12839247058823275503
Replicas:           1 desired | 1 total
Update Strategy:    RollingUpdate
Pods Status:        1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           alertmanager=stable-kube-prometheus-sta-alertmanager
                    app=alertmanager
                    app.kubernetes.io/instance=stable-kube-prometheus-sta-alertmanager
                    app.kubernetes.io/managed-by=prometheus-operator
                    app.kubernetes.io/name=alertmanager
                    app.kubernetes.io/version=0.22.2
  Annotations:      kubectl.kubernetes.io/default-container: alertmanager
  Service Account:  stable-kube-prometheus-sta-alertmanager
  Containers:
   alertmanager:
    Image:       quay.io/prometheus/alertmanager:v0.22.2
    Ports:       9093/TCP, 9094/TCP, 9094/UDP
    Host Ports:  0/TCP, 0/TCP, 0/UDP
    Args:
      --config.file=/etc/alertmanager/config/alertmanager.yaml
      --storage.path=/alertmanager
      --data.retention=120h
      --cluster.listen-address=
      --web.listen-address=:9093
      --web.external-url=http://stable-kube-prometheus-sta-alertmanager.default:9093
      --web.route-prefix=/
      --cluster.peer=alertmanager-stable-kube-prometheus-sta-alertmanager-0.alertmanager-operated:9094
      --cluster.reconnect-timeout=5m
    Requests:
      memory:   200Mi
    Liveness:   http-get http://:web/-/healthy delay=0s timeout=3s period=10s #success=1 #failure=10
    Readiness:  http-get http://:web/-/ready delay=3s timeout=3s period=5s #success=1 #failure=10
    Environment:
      POD_IP:   (v1:status.podIP)
    Mounts:
      /alertmanager from alertmanager-stable-kube-prometheus-sta-alertmanager-db (rw)
      /etc/alertmanager/certs from tls-assets (ro)
      /etc/alertmanager/config from config-volume (rw)
   config-reloader:
    Image:      quay.io/prometheus-operator/prometheus-config-reloader:v0.48.1
    Port:       8080/TCP
    Host Port:  0/TCP
    Command:
      /bin/prometheus-config-reloader
    Args:
      --listen-address=:8080
      --reload-url=http://127.0.0.1:9093/-/reload
      --watched-dir=/etc/alertmanager/config
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:     100m
      memory:  50Mi
    Environment:
      POD_NAME:   (v1:metadata.name)
      SHARD:     -1
    Mounts:
      /etc/alertmanager/config from config-volume (ro)
  Volumes:
   config-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-stable-kube-prometheus-sta-alertmanager-generated
    Optional:    false
   tls-assets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  alertmanager-stable-kube-prometheus-sta-alertmanager-tls-assets
    Optional:    false
   alertmanager-stable-kube-prometheus-sta-alertmanager-db:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Volume Claims:  <none>
Events:         <none>
