# config.yaml

worker:
  replicas: 1
  resources:
    limits:
      cpu: 8
      memory: 16G
    requests: 
      cpu: 8
      memory: 16G
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: -c conda-forge prophet 
    - name: EXTRA_PIP_PACKAGES
      value: pandas==1.2.5 pymongo sklearn blosc lz4     


# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: false
  env:
    - name: EXTRA_PIP_PACKAGES
      value: pandas==1.2.5      
    - name: EXTRA_CONDA_PACKAGES
      value: -c conda-forge prophet
