apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: "manual"
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
