apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed-nfs-storage 
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /s/lattice-0/b/lattice-kubernetes-c2
    server: lattice-0
